-- Chunk 4/7: re-tag segment em ~575 contactos
update public.outreach_contacts c
   set segment = m.seg
  from (values
    ('info@ericeirasurf.com', 'Surf school / club'),
    ('info@surfsolutions.pt', 'Surf school / club'),
    ('activitysurfcenter@gmail.com', 'Surf school / club'),
    ('info@ericeirasurfcamp.com', 'Surf school / club'),
    ('info@surfiteasy.pt', 'Surf school / club'),
    ('info@penichesupschool.com', 'Surf school / club'),
    ('escola.surf.peniche@gmail.com', 'Surf school / club'),
    ('info@penichesurfcamp.com', 'Surf school / club'),
    ('baleal@balealsurfcamp.com', 'Surf school / club'),
    ('info@surfingsilvercoast.com', 'Surf school / club'),
    ('happydayssurfpeniche@gmail.com', 'Surf school / club'),
    ('info@riparsurfschool.com', 'Surf school / club'),
    ('info@geckosurfschool.com', 'Surf school / club'),
    ('geral@caparicablueocean.com', 'Surf school / club'),
    ('surfprosurfschool@gmail.com', 'Surf school / club'),
    ('info@lisbonsurfcenter.com', 'Surf school / club'),
    ('csa@caparicasurfacademy.com', 'Surf school / club'),
    ('info@tikisurfacademy.com', 'Surf school / club'),
    ('info@drbernard.co', 'Surf school / club'),
    ('info@fishsurfschool.com', 'Surf school / club'),
    ('surftrainingschool@gmail.com', 'Surf school / club'),
    ('bsurfporto@gmail.com', 'Surf school / club'),
    ('info@saltywavesurf.com', 'Surf school / club'),
    ('info@algarvesurfschool.com', 'Surf school / club'),
    ('sagressurfschool@gmail.com', 'Surf school / club'),
    ('contact@thesurfexperience.eu', 'Surf school / club'),
    ('info@wavesensations.pt', 'Surf school / club'),
    ('office@missiontosurf.at', 'Surf school / club'),
    ('lisbonsurfaris@gmail.com', 'Surf school / club'),
    ('info@surfcascais.com', 'Surf school / club'),
    ('saltysoulspt@gmail.com', 'Surf school / club'),
    ('sansebastian@pukassurfeskola.com', 'Surf school / club'),
    ('reservas.beraberasurf@gmail.com', 'Surf school / club'),
    ('club@grosekoindarra.com', 'Surf school / club'),
    ('ecsurf@escuelacantabradesurf.com', 'Surf school / club'),
    ('info@latassurfhouse.com', 'Surf school / club'),
    ('koa@koaescueladesurf.com', 'Surf school / club'),
    ('info@awasurf.es', 'Surf school / club'),
    ('info@skoolsurf.com', 'Surf school / club'),
    ('escuela@siroko.com', 'Surf school / club'),
    ('info@tablassurfschool.com', 'Surf school / club'),
    ('escueladesurflongbeach@gmail.com', 'Surf school / club'),
    ('info@alamarsalinas.com', 'Surf school / club'),
    ('ffsurfschool@gmail.com', 'Surf school / club'),
    ('contacto@alawasurfcamp.com', 'Surf school / club'),
    ('info@santiagodepantin.com', 'Surf school / club'),
    ('info@valdosurf.com', 'Surf school / club'),
    ('info@southcoast.es', 'Surf school / club'),
    ('info@escueladesurfconil.com', 'Surf school / club'),
    ('info@surfclubelpalmar.com', 'Surf school / club'),
    ('info@canarysurfacademy.com', 'Surf school / club'),
    ('info@calimasurf.com', 'Surf school / club'),
    ('info@surfschoolanzarote.com', 'Surf school / club'),
    ('info@oceansidegrancanaria.com', 'Surf school / club'),
    ('info@surf-canaries.com', 'Surf school / club'),
    ('parnetyo@yahoo.fr', 'Surf school / club'),
    ('infosurftrip40@gmail.com', 'Surf school / club'),
    ('info@naturalsurflodge.com', 'Surf school / club'),
    ('plums@wanadoo.fr', 'Surf school / club'),
    ('contact@hastea.com', 'Surf school / club'),
    ('straightupbiarritz@gmail.com', 'Surf school / club'),
    ('info@surftraining.com', 'Surf school / club'),
    ('bidartsurfacademy@gmail.com', 'Surf school / club'),
    ('aolasurf@gmail.com', 'Surf school / club'),
    ('contact@surfguidelacanau.com', 'Surf school / club'),
    ('ecole@kalanisurf.com', 'Surf school / club'),
    ('bigmamasurfschool@gmail.com', 'Surf school / club'),
    ('jltcsurfschool@gmail.com', 'Surf school / club'),
    ('contact@ecoledesurf-rainbow.com', 'Surf school / club'),
    ('contact@seignosse-surf-school.com', 'Surf school / club'),
    ('contact@authentique-ecoledesurf.com', 'Surf school / club'),
    ('contact@aloha-ecoledesurf.com', 'Surf school / club'),
    ('esbsurfclub@gmail.com', 'Surf school / club'),
    ('esbpenhors29@gmail.com', 'Surf school / club'),
    ('contact@magnetsurf.com', 'Surf school / club'),
    ('info@boardnbreakfast.com', 'Surf school / club'),
    ('info@dutchsurfacademy.nl', 'Surf school / club'),
    ('surfschool@alohasurf.nl', 'Surf school / club'),
    ('surfschool@hartbeach.nl', 'Surf school / club'),
    ('info@surfersparadise.be', 'Surf school / club'),
    ('hello@cornishwave.com', 'Surf school / club'),
    ('info@escapesurfschool.co.uk', 'Surf school / club'),
    ('weridesurfschool18@gmail.com', 'Surf school / club'),
    ('banzaisurfschool@gmail.com', 'Surf school / club'),
    ('tortugasurfschool@gmail.com', 'Surf school / club'),
    ('buggerrusurfschool@hotmail.com', 'Surf school / club'),
    ('support@eisbach-riders.com', 'Surf school / club'),
    ('info@lapointcamps.com', 'Surf camp'),
    ('emanueltonet@hotmail.com', 'Surf school / club'),
    ('fps@surfingportugal.com', 'Surf federation / association'),
    ('ericeirasurfclube@gmail.com', 'Surf school / club'),
    ('info@surfingviana.com', 'Surf school / club'),
    ('administracion@fesurf.es', 'Surf federation / association'),
    ('contact@surfingfrance.com', 'Surf federation / association'),
    ('info@surfingengland.org', 'Surf federation / association'),
    ('admin@wsf.wales', 'Surf federation / association'),
    ('info@irishsurfing.ie', 'Surf federation / association'),
    ('info@hsa.nl', 'Surf federation / association'),
    ('info@wellenreitverband.de', 'Surf federation / association'),
    ('parcerias@esnlisboa.org', 'University / student'),
    ('relacoes.externas@esnporto.org', 'University / student'),
    ('partnerships@esncoimbra.org', 'University / student'),
    ('info@esnportugal.org', 'University / student'),
    ('partners@esnmadrid.org', 'University / student'),
    ('info@esn-ub.org', 'University / student'),
    ('secretary@esnupf.org', 'University / student'),
    ('junta@upv.esnvlc.es', 'University / student'),
    ('junta@esnuv.org', 'University / student'),
    ('junta@esnsevilla.org', 'University / student'),
    ('info@esngranada.org', 'University / student'),
    ('spain@esn.org', 'University / student'),
    ('info@esn.paris', 'University / student'),
    ('contact@cosmolyon.com', 'University / student'),
    ('esnbordeaux@ixesn.fr', 'University / student'),
    ('contact@esntoulouse.com', 'University / student'),
    ('esn.nantes@gmail.com', 'University / student'),
    ('info@esn-amsterdam.nl', 'University / student'),
    ('president@esndelft.nl', 'University / student'),
    ('info@esn-rotterdam.nl', 'University / student'),
    ('info@esn-groningen.nl', 'University / student'),
    ('board@esnleuven.be', 'University / student'),
    ('esn.gent@gmail.com', 'University / student'),
    ('esn-berlin@esn-germany.de', 'University / student'),
    ('board@esn-tumi.de', 'University / student'),
    ('welcome@esnbologna.org', 'University / student'),
    ('milano_statale@esn.it', 'University / student'),
    ('info@esnpolimi.it', 'University / student'),
    ('roma_ase@esn.it', 'University / student'),
    ('pisa@esn.it', 'University / student'),
    ('firenze@esn.it', 'University / student'),
    ('board@esnstockholm.org', 'University / student'),
    ('info@esn-cph.dk', 'University / student'),
    ('president-aarhus@esndenmark.org', 'University / student'),
    ('info@susurf.co.uk', 'Surf school / club'),
    ('surfing@upsu.net', 'Surf school / club'),
    ('upscsurf@hotmail.com', 'Surf school / club'),
    ('surfing@ed.ac.uk', 'Surf school / club'),
    ('surf@gcustudents.co.uk', 'Surf school / club'),
    ('surfclub@aber.ac.uk', 'Surf school / club'),
    ('desporto@aaualg.pt', 'University / student'),
    ('info@rayburntours.com', 'Travel agency / DMC'),
    ('enquiries@halsbury.com', 'Travel agency / DMC'),
    ('mknowles@nstgroup.co.uk', 'Travel agency / DMC'),
    ('enquiries@pgl.co.uk', 'Travel agency / DMC'),
    ('info@acornadventure.co.uk', 'Travel agency / DMC'),
    ('ed@edwindoran.com', 'Travel agency / DMC'),
    ('info@angloeducational.com', 'Travel agency / DMC'),
    ('customer.service@ef.com', 'Travel agency / DMC'),
    ('skern@skernlodge.co.uk', 'Other'),
    ('enquiries@jca-adventure.co.uk', 'Travel agency / DMC'),
    ('enquiries@selectschooltours.com', 'Travel agency / DMC'),
    ('info@schoolsintoeurope.com', 'Travel agency / DMC'),
    ('info@kiplingtours.com', 'Travel agency / DMC'),
    ('rachael.mcloughlin@thelearningadventure.com', 'Travel agency / DMC'),
    ('info@cts-reisen.de', 'Travel agency / DMC'),
    ('kontakt@herole.de', 'Travel agency / DMC'),
    ('gruppen@ruf.de', 'Travel agency / DMC'),
    ('info@kluehspies.com', 'Travel agency / DMC'),
    ('groups@schuster-reisen.com', 'Travel agency / DMC'),
    ('info@schulfahrt.de', 'Travel agency / DMC'),
    ('office@senlactours.com', 'Travel agency / DMC'),
    ('klantenservice@snp.nl', 'Travel agency / DMC'),
    ('graeme@smilegrouptravel.com', 'Travel agency / DMC'),
    ('michael@sportagroup.com', 'Travel agency / DMC'),
    ('annette@robinsonscandinavia.com', 'Travel agency / DMC'),
    ('info@pathwaysedu.org', 'Travel agency / DMC'),
    ('info@scoutisme-francais.org', 'University / student'),
    ('contact@sgdf.fr', 'University / student'),
    ('europe@scout.org', 'University / student'),
    ('info@surfholidays.com', 'Travel agency / DMC'),
    ('info@theperfectwave.com.au', 'Travel agency / DMC'),
    ('info@surfawhile.com', 'Travel agency / DMC'),
    ('wavehunters@wavehunters.com', 'Travel agency / DMC'),
    ('tim@luex.com', 'Travel agency / DMC'),
    ('info@worldsurfaris.com', 'Travel agency / DMC'),
    ('sean@waterwaystravel.com', 'Travel agency / DMC'),
    ('mees@surfawhile.com', 'Travel agency / DMC'),
    ('travelteam@euroventure.com', 'Travel agency / DMC'),
    ('partner@moverii.de', 'Travel agency / DMC'),
    ('aurora@booksurfcamps.com', 'Travel agency / DMC'),
    ('portugal@liberty-int.com', 'Travel agency / DMC'),
    ('geral@widetravel.pt', 'Travel agency / DMC'),
    ('portugal@ovationdmc.com', 'Travel agency / DMC'),
    ('events@insideeventsdmc.com', 'Travel agency / DMC'),
    ('info@retreathub.com', 'Yoga / wellness retreat'),
    ('hello@experienceretreats.com', 'Yoga / wellness retreat'),
    ('media@tickettoridegroup.com', 'University / student'),
    ('ucscsurfteam@gmail.com', 'Surf school / club'),
    ('theucsbsurfteam@gmail.com', 'Surf school / club'),
    ('recreation-ucsbsportclub.surfing@ucsb.edu', 'Surf school / club'),
    ('ucsandiegosurfteam@gmail.com', 'Surf school / club'),
    ('sportclubs@sdsu.edu', 'Surf school / club'),
    ('asiclubservices@calpoly.edu', 'Surf school / club'),
    ('ingrid.corleto101@csuci.edu', 'Surf school / club'),
    ('csusmsurf@gmail.com', 'Surf school / club'),
    ('julian.baker@pepperdine.edu', 'Surf school / club'),
    ('campusrecreation@sandiego.edu', 'Surf school / club'),
    ('deanofstudents@salve.edu', 'Surf school / club'),
    ('compsports@uncw.edu', 'Surf school / club'),
    ('sportclubs@utrecsports.org', 'University / student'),
    ('q.cavalli@northeastern.edu', 'Surf school / club'),
    ('unfsurfteam@gmail.com', 'Surf school / club'),
    ('clubhouse@recreation.ucla.edu', 'Surf school / club'),
    ('uscsurfteam@gmail.com', 'Surf school / club'),
    ('scsurfriderclub@gmail.com', 'Surf school / club'),
    ('mnorris1@coastal.edu', 'Surf school / club'),
    ('clubsports@csulb.edu', 'Surf school / club'),
    ('stanfordaquatics@stanford.edu', 'Surf school / club'),
    ('johnsonb@tamug.edu', 'University / student'),
    ('crwsportprograms@ecu.edu', 'University / student'),
    ('cofcwatersportsclub@gmail.com', 'Surf school / club'),
    ('lmuclubsports@lmu.edu', 'Surf school / club'),
    ('recreation@ucsd.edu', 'University / student'),
    ('recreation@northeastern.edu', 'University / student'),
    ('surfing@lasolas.surf', 'Yoga / wellness retreat'),
    ('hello@surfwithamigas.com', 'Yoga / wellness retreat'),
    ('info@stoketravel.com', 'Travel agency / DMC'),
    ('askadiva@surfdiva.com', 'Yoga / wellness retreat'),
    ('hello@lushpalm.com', 'Surf school / club'),
    ('help@thermal.travel', 'Travel agency / DMC'),
    ('info@outerreefsurftravel.com', 'Travel agency / DMC'),
    ('hello@stokedsurfadventures.com', 'Travel agency / DMC'),
    ('surfexpressfl@gmail.com', 'Travel agency / DMC'),
    ('info@thesurftribe.com', 'Surf school / club'),
    ('help@surftripsupply.com', 'Travel agency / DMC'),
    ('info@puresurfcamps.com', 'Surf camp'),
    ('office@surfsister.com', 'Surf school / club'),
    ('info@pacificsurfschool.com', 'Surf school / club'),
    ('info@tofinosurfadventures.ca', 'Surf school / club'),
    ('info@swelltofino.com', 'Surf school / club'),
    ('clubs@ams.ubc.ca', 'Surf school / club'),
    ('execuvicsurf@gmail.com', 'Surf school / club'),
    ('daloutdoors@dal.ca', 'University / student'),
    ('sales@adventures-abroad.com', 'Travel agency / DMC'),
    ('info@merittravel.com', 'Travel agency / DMC'),
    ('emily.mikus@gadventures.com', 'Travel agency / DMC'),
    ('help@contiki.com', 'Travel agency / DMC'),
    ('info@westtrek.com', 'University / student'),
    ('info@freshadventures.com', 'Travel agency / DMC'),
    ('clubs@activateuts.com.au', 'Surf school / club'),
    ('surfing.club@rmit.edu.au', 'Surf school / club'),
    ('musurf@gmail.com', 'Surf school / club'),
    ('surf@monashboardriders.com', 'Surf school / club'),
    ('sydneyunisurfing@gmail.com', 'Surf school / club'),
    ('clubs@arc.unsw.edu.au', 'Surf school / club'),
    ('guildclubs@griffith.edu.au', 'University / student'),
    ('clubs@guild.curtin.edu.au', 'Surf school / club'),
    ('soc-president@guild.uwa.edu.au', 'University / student'),
    ('uniofwollongong@surfrider.org.au', 'Surf school / club'),
    ('qutsurfers@gmail.com', 'Surf school / club'),
    ('studentassociation@jcu.edu.au', 'Surf school / club'),
    ('studentgroups@auckland.ac.nz', 'Surf school / club'),
    ('wsu@wsu.org.nz', 'Surf school / club'),
    ('clubsandsocs@ousa.org.nz', 'University / student'),
    ('clubs@musa.org.nz', 'Surf school / club'),
    ('student-services@vuw.ac.nz', 'University / student'),
    ('info@roc.org.au', 'University / student'),
    ('enquiries@monashclubs.org', 'University / student'),
    ('info@atolltravel.com', 'Travel agency / DMC'),
    ('enquiries@surftravel.com.au', 'Travel agency / DMC'),
    ('info@mojosurf.com', 'Surf camp'),
    ('info@australiansurfingadventures.com', 'Travel agency / DMC'),
    ('info@surfingaustralia.com', 'Surf federation / association'),
    ('surf@surfaris.com', 'Yoga / wellness retreat'),
    ('studentaffairs@aus.edu', 'University / student'),
    ('studentaffairs@zu.ac.ae', 'University / student'),
    ('admissions@ku.ac.ae', 'University / student'),
    ('info@ud.ac.ae', 'University / student'),
    ('dubaienquiries@hw.ac.uk', 'University / student'),
    ('admissions@mdx.ac.ae', 'University / student'),
    ('info@aud.edu', 'University / student'),
    ('schelpdesk@kaust.edu.sa', 'University / student'),
    ('info@dcc.kfupm.edu.sa', 'University / student'),
    ('effatuniversity@effatuniversity.edu.sa', 'University / student'),
    ('info@alfaisal.edu', 'University / student'),
    ('qumcc@qu.edu.qa', 'University / student'),
    ('info@surfingdubai.com', 'Surf school / club'),
    ('press@wadiadventure.ae', 'Surf school / club'),
    ('info@surfclubdubai.com', 'Other'),
    ('go@dukite.com', 'Surf school / club'),
    ('joinus@adventurati-outdoor.com', 'Other'),
    ('info@hattawadiadventure.com', 'Other'),
    ('info@absolute-adventure.com', 'Other'),
    ('aaonline@arabian-adventures.com', 'Travel agency / DMC'),
    ('dubaisales@eaglecrestdmc.com', 'Travel agency / DMC'),
    ('alberto@impactdmc.com', 'Travel agency / DMC'),
    ('info@magic-dmc.com', 'Travel agency / DMC'),
    ('info@pure-arabia.com', 'Travel agency / DMC'),
    ('arabia@ovationdmc.com', 'Travel agency / DMC'),
    ('porus@incentiveconnections.com', 'Travel agency / DMC'),
    ('info@2xceed.com', 'Travel agency / DMC'),
    ('info@88destinations.com', 'Travel agency / DMC'),
    ('saudi@tetrapylon.com', 'Travel agency / DMC'),
    ('info@icom-dmc.org', 'Travel agency / DMC'),
    ('info@dmcdoha.com', 'Travel agency / DMC'),
    ('qatar@a-dmcglobal.com', 'Travel agency / DMC'),
    ('info@wealthofwellness.org', 'Yoga / wellness retreat'),
    ('info@soulandskinwellness.com', 'Yoga / wellness retreat'),
    ('contact@artoflivingme.org', 'Yoga / wellness retreat'),
    ('info@yogaone.ae', 'Yoga / wellness retreat'),
    ('info@opencircleyoga.org', 'Yoga / wellness retreat'),
    ('info@tridentwellnessdubai.com', 'Yoga / wellness retreat'),
    ('info@villasage.ae', 'Yoga / wellness retreat'),
    ('art.of.yogaa@gmail.com', 'Yoga / wellness retreat'),
    ('enquiries@soulandsurf.com', 'Yoga / wellness retreat'),
    ('hello@riseupsurf.com', 'Yoga / wellness retreat'),
    ('info@puravidaadventures.com', 'Yoga / wellness retreat'),
    ('info@bodhisurfyoga.com', 'Yoga / wellness retreat'),
    ('surfsistas@gmail.com', 'Yoga / wellness retreat'),
    ('amouage@surfmaroc.com', 'Yoga / wellness retreat'),
    ('info@surfivorcamp.com', 'Yoga / wellness retreat'),
    ('info@starsurfcamps.com', 'Yoga / wellness retreat'),
    ('office@wavetours.com', 'Travel agency / DMC'),
    ('womensoulfulsurf@gmail.com', 'Yoga / wellness retreat'),
    ('cascais@thesalty.co', 'Yoga / wellness retreat'),
    ('hello@surfergoddessretreats.com', 'Yoga / wellness retreat'),
    ('bluemind@bananasurfmorocco.com', 'Yoga / wellness retreat'),
    ('hello@lavidasurf.com', 'Yoga / wellness retreat'),
    ('contact@rebornsurfcamp.com', 'Yoga / wellness retreat'),
    ('info@eatpraymove.com', 'Yoga / wellness retreat'),
    ('katieschiffgen@me.com', 'Yoga / wellness retreat'),
    ('wholebodyparadigm@gmail.com', 'Yoga / wellness retreat'),
    ('info@nectaryoga.ca', 'Yoga / wellness retreat'),
    ('info@internationalyoga.com', 'Yoga / wellness retreat'),
    ('montreal@sivananda.org', 'Yoga / wellness retreat'),
    ('info@tripaneer.com', 'Yoga / wellness retreat'),
    ('sean@bookretreats.com', 'Yoga / wellness retreat'),
    ('support@retreat.guru', 'Yoga / wellness retreat'),
    ('hello@venueretreat.com', 'Yoga / wellness retreat'),
    ('marina@retreatsandvenues.com', 'Yoga / wellness retreat'),
    ('bookings@nomadsurfers.com', 'Travel agency / DMC'),
    ('contact@360-surf.com', 'Travel agency / DMC'),
    ('info@planetsurfcamps.com', 'Travel agency / DMC'),
    ('james@awavetravel.com', 'Travel agency / DMC'),
    ('cbcm.islands@outlook.com', 'Travel agency / DMC'),
    ('contact@rapturecamps.com', 'Surf camp'),
    ('contact@surfberbere.com', 'Surf camp'),
    ('surf@mellowmove.com', 'Surf camp'),
    ('info@surfcamp-online.com', 'Surf camp'),
    ('originalsurfmorocco@gmail.com', 'Surf camp'),
    ('info@morocsurf.com', 'Yoga / wellness retreat'),
    ('surfcamps@wellenreiter.com', 'Surf camp'),
    ('hello@thesurfoffice.com', 'Corporate / offsite / group'),
    ('thomas@teamout.com', 'Corporate / offsite / group'),
    ('jake@offsite.com', 'Corporate / offsite / group'),
    ('sean@monikerpartners.com', 'Corporate / offsite / group'),
    ('inquiries@flok.com', 'Corporate / offsite / group'),
    ('support@nextretreat.com', 'Yoga / wellness retreat'),
    ('indrajit@boompop.com', 'Corporate / offsite / group'),
    ('suman@marcoexperiences.com', 'Corporate / offsite / group'),
    ('info@pencilandpaper.ca', 'Corporate / offsite / group'),
    ('elisa@outsite.co', 'Yoga / wellness retreat'),
    ('hello@wifitribe.co', 'Corporate / offsite / group'),
    ('mauro@boundless.life', 'Corporate / offsite / group'),
    ('facilitators@hackerparadise.org', 'Corporate / offsite / group'),
    ('info@ninecoliving.com', 'Corporate / offsite / group'),
    ('edu@sun-and-co.com', 'Corporate / offsite / group'),
    ('contact@sende.co', 'Corporate / offsite / group'),
    ('workation@coconat-space.com', 'Yoga / wellness retreat'),
    ('info@mokrinhouse.com', 'Yoga / wellness retreat'),
    ('hi@coworksurf.com', 'Yoga / wellness retreat'),
    ('michelle@thenomadescape.com', 'Yoga / wellness retreat'),
    ('johannes@nomadcruise.com', 'Corporate / offsite / group'),
    ('info@noma-collective.com', 'Corporate / offsite / group'),
    ('monestevole@tribewanted.com', 'Yoga / wellness retreat'),
    ('maxime@naboo.app', 'Corporate / offsite / group'),
    ('contact@myeventconcierge.co.uk', 'Corporate / offsite / group'),
    ('hello@gobehere.com', 'Corporate / offsite / group'),
    ('hello@pissup.com', 'Corporate / offsite / group'),
    ('stag@stagweb.co.uk', 'Corporate / offsite / group'),
    ('feedback@thestagcompany.com', 'Corporate / offsite / group'),
    ('info@designaventure.co.uk', 'Corporate / offsite / group'),
    ('maximise@maximise.co.uk', 'Corporate / offsite / group'),
    ('bookings@stagit.ie', 'Corporate / offsite / group'),
    ('katie@lastnightoffreedom.co.uk', 'Corporate / offsite / group'),
    ('enquiries@gobananas.com', 'Corporate / offsite / group'),
    ('emmap@chillisauce.com', 'Corporate / offsite / group'),
    ('ross@thestagandhenexperience.co.uk', 'Corporate / offsite / group'),
    ('admin@pinkmonkeystagandhen.co.uk', 'Corporate / offsite / group'),
    ('enquiries@portugalrocks.com', 'Corporate / offsite / group'),
    ('info@thespainevent.com', 'Corporate / offsite / group'),
    ('hello@veryintopartying.com', 'Corporate / offsite / group'),
    ('hostsupport@trovatrip.com', 'Corporate / offsite / group'),
    ('info@wetravel.com', 'Corporate / offsite / group'),
    ('girlonthewave@gmail.com', 'Corporate / offsite / group'),
    ('readytoescape@flashpack.com', 'Other'),
    ('alex@muchbetteradventures.com', 'Other'),
    ('info@intrepidtravel.com', 'Other'),
    ('jonny.bealby@wildfrontiers.co.uk', 'Other'),
    ('community@solofemaletravelers.club', 'Corporate / offsite / group'),
    ('hello@sofetravel.com', 'Corporate / offsite / group'),
    ('info@womens-travel-club.com', 'Corporate / offsite / group'),
    ('phyllis@thewomenstravelgroup.com', 'Corporate / offsite / group'),
    ('info@sisterhoodtravels.com', 'Corporate / offsite / group'),
    ('support@wildwomenexpeditions.com', 'Corporate / offsite / group'),
    ('info@adventurousewe.co.uk', 'Travel agency / DMC'),
    ('hatty@womenandwavessociety.com', 'Corporate / offsite / group'),
    ('info@chicksonwaves.com', 'Yoga / wellness retreat'),
    ('rebellesurf@gmail.com', 'Corporate / offsite / group'),
    ('info@sligosurfexperience.com', 'Surf school / club'),
    ('info@surfsligo.com', 'Surf school / club'),
    ('info@saltysoulsexperience.com', 'Yoga / wellness retreat'),
    ('info@reiseathleten.de', 'Fitness / running / CrossFit'),
    ('info@crossfitmunich.com', 'Fitness / running / CrossFit'),
    ('info@crossfitnordic.se', 'Fitness / running / CrossFit'),
    ('eivind@ringard.no', 'Fitness / running / CrossFit'),
    ('info@tritrainingharder.com', 'Fitness / running / CrossFit'),
    ('enquiries@totaltritraining.com', 'Fitness / running / CrossFit'),
    ('info@209events.com', 'Fitness / running / CrossFit'),
    ('info@fullpotential.co.uk', 'Fitness / running / CrossFit'),
    ('info@runningwithus.com', 'Fitness / running / CrossFit'),
    ('claire@runscapeadventures.co.uk', 'Fitness / running / CrossFit'),
    ('info@swimmingtrainingcamps.com', 'Fitness / running / CrossFit'),
    ('info@swimtrainingcamps.com', 'Fitness / running / CrossFit'),
    ('secretary.maidstonesc@hotmail.com', 'Fitness / running / CrossFit'),
    ('secretary@chalfontotters.org.uk', 'Fitness / running / CrossFit'),
    ('rowing@gofigueira.com', 'Fitness / running / CrossFit'),
    ('info@movesports.com', 'Other'),
    ('info@sports-ventures.com', 'Travel agency / DMC'),
    ('info@soccatours.com', 'Fitness / running / CrossFit'),
    ('info@algarvefootballtours.com', 'Fitness / running / CrossFit'),
    ('regardt@browns-club.com', 'Other'),
    ('the-campus@quintadolago.com', 'Other'),
    ('hello@rugbytravelireland.com', 'Fitness / running / CrossFit'),
    ('contact@absolutetravel.co.uk', 'Travel agency / DMC'),
    ('info@no1bootcamp.com', 'Yoga / wellness retreat'),
    ('sales@motivatebootcamp.co.uk', 'Fitness / running / CrossFit'),
    ('retreats@rwl.fitness', 'Yoga / wellness retreat'),
    ('info@unitrips.org', 'Travel agency / DMC'),
    ('mobilityfriends@gmail.com', 'University / student'),
    ('alumni@aesu.com', 'Travel agency / DMC'),
    ('rustic@rusticpathways.com', 'University / student'),
    ('inquire@ciee.org', 'School / education'),
    ('aifsabroad@aifs.com', 'School / education'),
    ('portuguese@cial.pt', 'School / education'),
    ('contact@lusaschool.com', 'School / education'),
    ('info@portugueseconnection.pt', 'School / education'),
    ('reservas@pousadasjuventude.pt', 'University / student'),
    ('info@hihostels.com', 'Surf federation / association'),
    ('customerservices@yha.org.uk', 'University / student'),
    ('hauptverband@jugendherberge.de', 'University / student'),
    ('info@iyha.org.il', 'University / student'),
    ('contato@welcomesurftrips.com.br', 'Travel agency / DMC'),
    ('bahiasurfcamp@bahiasurfcamp.com', 'Surf school / club'),
    ('office@easydrop.com', 'Surf school / club'),
    ('surfaventura@gmail.com', 'Surf school / club'),
    ('info@associacaoescolasdesurf.pt', 'Surf federation / association'),
    ('info@tlvsurf.com', 'Surf school / club'),
    ('topseainfo@gmail.com', 'Surf school / club'),
    ('info@southafricasurftours.com', 'Travel agency / DMC'),
    ('jenya@unravelsurftravel.com', 'Travel agency / DMC'),
    ('contato@raizessurf.com.br', 'Surf school / club'),
    ('onescoladesurf@gmail.com', 'Surf school / club'),
    ('contato@maresiastur.com.br', 'Travel agency / DMC'),
    ('contato@uuhull.com', 'Surf school / club'),
    ('michel@auladesurfubatuba.com.br', 'Surf school / club'),
    ('contato@fresiasurfclass.com.br', 'Surf school / club'),
    ('escoladesurfrico@globo.com', 'Surf school / club'),
    ('escoladesurfsaqua@hotmail.com', 'Surf school / club'),
    ('contato@institutocarioca.org.br', 'Surf school / club'),
    ('greenhousesaqua@gmail.com', 'Surf school / club'),
    ('floripasurfclub@gmail.com', 'Surf school / club'),
    ('campechesurfschool@hotmail.com', 'Surf school / club'),
    ('dedabarra@hotmail.com', 'Surf school / club'),
    ('marcopolosurfescola@gmail.com', 'Surf school / club'),
    ('atendimento@aosulnatural.com.br', 'Surf school / club'),
    ('pipasurfschool@gmail.com', 'Surf school / club'),
    ('gildapipa@hotmail.com', 'Surf school / club'),
    ('info@thesurfscool.com', 'Surf school / club'),
    ('arthurpeandrade@gmail.com', 'Surf school / club'),
    ('surftravel@surftravel.com.br', 'Travel agency / DMC'),
    ('sas@cbsurf.org.br', 'Surf federation / association'),
    ('info@bsc.surf', 'Surf school / club'),
    ('contato@asgsurf.com.br', 'Surf federation / association'),
    ('contato@feserj.org.br', 'Surf federation / association'),
    ('contatospsurf@gmail.com', 'Surf federation / association'),
    ('contato@ecoturismobrasil.com.br', 'Travel agency / DMC'),
    ('biotrip@biotrip.com.br', 'Travel agency / DMC'),
    ('bookings@under30experiences.com', 'Other'),
    ('partnerships@trutravels.com', 'Corporate / offsite / group'),
    ('tushar@tourhero.com', 'Corporate / offsite / group'),
    ('contact@goaheadtours.com', 'Corporate / offsite / group'),
    ('hello@morelifeadventures.com', 'Yoga / wellness retreat'),
    ('info@activeescapes.com', 'Yoga / wellness retreat'),
    ('info@wildfitness.com', 'Yoga / wellness retreat'),
    ('mail@wanderlustyoga.info', 'Yoga / wellness retreat'),
    ('jen@thetravelyogi.com', 'Yoga / wellness retreat'),
    ('info@truenaturetravels.com', 'Yoga / wellness retreat'),
    ('info@treetopyoga.com', 'Yoga / wellness retreat'),
    ('info@escapehaven.com', 'Yoga / wellness retreat'),
    ('hello@wodholidays.com', 'Yoga / wellness retreat'),
    ('info@barrefitness.com', 'Yoga / wellness retreat'),
    ('hello@breathemovementstudios.com', 'Yoga / wellness retreat'),
    ('hello@anasapilates.co.uk', 'Yoga / wellness retreat'),
    ('info@coreconnexion.co.uk', 'Yoga / wellness retreat'),
    ('info@yogalap.com', 'Yoga / wellness retreat'),
    ('steven@breathlife.co.uk', 'Yoga / wellness retreat'),
    ('leonor@myalfazema.com', 'Yoga / wellness retreat'),
    ('partnerships@midnightrunners.com', 'Fitness / running / CrossFit'),
    ('bookings@compareretreats.com', 'Yoga / wellness retreat'),
    ('arnhem@luzac.nl', 'School / education'),
    ('lyceumamsterdam@luzac.nl', 'School / education'),
    ('info@unifac.be', 'University / student'),
    ('info@aegee-utrecht.nl', 'University / student'),
    ('zwolle@luzac.nl', 'School / education'),
    ('bestuur@utvweb.nl', 'University / student'),
    ('commercial@efr.nl', 'University / student'),
    ('info@faector.nl', 'University / student'),
    ('info@fsr.nl', 'University / student'),
    ('info@capitant.be', 'University / student'),
    ('administration@rijnlandslyceum-rlo.nl', 'School / education'),
    ('bestuur@ubv.info', 'University / student'),
    ('board@ulsvamino.nl', 'University / student'),
    ('info@derm.nl', 'University / student'),
    ('info@inbl.nl', 'School / education'),
    ('info@cedonulli.nl', 'University / student'),
    ('utrecht@luzac.nl', 'School / education'),
    ('info@alcmaeon.nl', 'University / student'),
    ('jss.erlenbach@phorms.de', 'School / education'),
    ('info@svvocus.nl', 'University / student'),
    ('board@aegee-nijmegen.nl', 'University / student'),
    ('rotterdam@luzac.nl', 'School / education'),
    ('info@aureus.nl', 'University / student'),
    ('info@uasportraad.be', 'University / student'),
    ('info@spin-utrecht.nl', 'University / student'),
    ('informacion@mascamarena.es', 'School / education'),
    ('admissions@aloha-college.com', 'School / education'),
    ('info@krumbach.school', 'School / education'),
    ('office@isc.ac.at', 'School / education'),
    ('info@willowinternationalschool.es', 'School / education'),
    ('info@svskmallorca.se', 'School / education'),
    ('info@wikings.be', 'University / student'),
    ('office@gibs.at', 'School / education'),
    ('praesidium@arch.ethz.ch', 'University / student'),
    ('info@amiv.ethz.ch', 'University / student'),
    ('info@thamesbritishschool.es', 'School / education'),
    ('infozaragoza@iepgroup.es', 'School / education'),
    ('osg-contact@eursc.eu', 'School / education'),
    ('info@genoaschool.eu', 'School / education'),
    ('info@aislanzarote.com', 'School / education'),
    ('info@engelska.se', 'School / education'),
    ('extern@salus.online', 'University / student'),
    ('extern@subliem-vu.nl', 'University / student'),
    ('qbdbd.rechten@vu.nl', 'University / student'),
    ('extern@kraket.nl', 'University / student'),
    ('office@aegee-amsterdam.nl', 'University / student'),
    ('info@asvbuild.nl', 'University / student'),
    ('info@absoc.be', 'University / student'),
    ('info@mahara.be', 'University / student'),
    ('haarlem@luzac.nl', 'School / education'),
    ('praeses@campinaria.be', 'University / student'),
    ('info@comac-studenten.be', 'University / student'),
    ('info@amadeus-vienna.com', 'School / education'),
    ('info@isgenoa.it', 'School / education'),
    ('secretaria@colegio-mestral.com', 'School / education'),
    ('info@danubeschool.com', 'School / education'),
    ('admissions@st-georges.lu', 'School / education'),
    ('international.school.braunschweig@cjd.de', 'School / education'),
    ('secondary@ishthehague.nl', 'School / education'),
    ('south@bischool.com', 'School / education'),
    ('admin@internationalschooldelft.org', 'School / education'),
    ('rethink.econ.ita@gmail.com', 'University / student'),
    ('info@disdh.nl', 'School / education'),
    ('isw@rijnlandslyceum-rlw.nl', 'School / education'),
    ('info@ash.nl', 'School / education'),
    ('admissions@eshthehague.nl', 'School / education'),
    ('admin.riss@wolfert.nl', 'School / education'),
    ('info@vecht-college.nl', 'School / education'),
    ('info@isr-school.de', 'School / education'),
    ('leiden@luzac.nl', 'School / education'),
    ('alkmaar@luzac.nl', 'School / education'),
    ('amersfoort@luzac.nl', 'School / education'),
    ('hilversum@luzac.nl', 'School / education'),
    ('breda@luzac.nl', 'School / education'),
    ('denhaag@luzac.nl', 'School / education')
  ) as m(email, seg)
 where lower(c.email) = m.email;
